modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="decapitation" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Decapitated" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="multiloader.png" #optional

credits="Jared for the multiloader framework" #optional
authors="Lilypuree" #optional
description='''
adds decapitated mobs
'''

[[dependencies.decapitation]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.decapitation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
